using LagoVista.AI.Models;
using LagoVista.CloudStorage.DocumentDB;
using LagoVista.Core.Models;
using LagoVista.IoT.Logging.Loggers;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using LagoVista.Core;
using Microsoft.Azure.Cosmos.Linq;
using LagoVista.AI.Interfaces.Repos;

namespace LagoVista.AI.CloudRepos
{
    public class TlaCatalogRepo : DocumentDBRepoBase<DdrTlaCatalog>, ITlaCatalogRepo
    {
        public TlaCatalogRepo(IMLRepoSettings settings, IAdminLogger logger) :
            base(settings.MLDocDbStorage.Uri, settings.MLDocDbStorage.AccessKey, settings.MLDocDbStorage.ResourceName, logger)
        {
        }

        public async Task<DdrTlaCatalog> GetTlaCatalogAsync(EntityHeader org, EntityHeader user)
        {
            var catalog = await QueryAsync(qry => qry.OwnerOrganization.Id == org.Id);
            if(catalog.Any())
            {
                return catalog.First();
            }

            var newCatalog = new DdrTlaCatalog();
            newCatalog.OwnerOrganization = org;
            newCatalog.CreatedBy = user;
            newCatalog.LastUpdatedBy = user;
            newCatalog.CreationDate = UtcTimestamp.Now;
            newCatalog.LastUpdatedDate = newCatalog.CreationDate;
            newCatalog.Name = $"TLA Catalogfor {org.Text}.";
            newCatalog.Key = "autogenerated";
            await UpsertDocumentAsync(newCatalog);

            return newCatalog;
        }

        public Task UpdateTlaCatalog(DdrTlaCatalog ddrTla)
        {
            return UpsertDocumentAsync(ddrTla);;
        }
    }
}
